package Presentacion;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jean
 */
public class ComponenteCategoria extends javax.swing.JPanel {

    /**
     * Creates new form ComponenteCategoria
     *
     */
    private final int index;
    private final String nombre;
    public ComponenteCategoria(int index,String nombre) {
       initComponents();
        this.index = index;
        this.nombre = nombre;
        valor.setText(this.index+" - "+nombre);
        this.valor.setActionCommand("key_" + index);
    }
    public javax.swing.JCheckBox getValor(){
        return valor;
    }
    public int getIndex(){
        return index;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        valor = new javax.swing.JCheckBox();

        setMaximumSize(new java.awt.Dimension(120, 30));
        setMinimumSize(new java.awt.Dimension(140, 30));

        valor.setText("Nombre Categoria");
        valor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(valor, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(valor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox valor;
    // End of variables declaration//GEN-END:variables
}
