package Presentacion;

import Logica.FileController;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Jean
 */
public class ComponenteImagen extends javax.swing.JPanel {

    private final PanelImagenes contenedor;
    private final String Path_Img;
    private final String nombre;
    private final int index;

    /**
     * Creates new form ComponenteImagen
     *
     * @param index
     * @param nombre
     * @param Path_Img
     * @param contenedor
     */
    public ComponenteImagen(int index, String nombre, String Path_Img, PanelImagenes contenedor) {
        initComponents();
        this.Path_Img = Path_Img;
        this.nombre = nombre;
        this.index = index;
        this.jButton1.setActionCommand("key_" + index);
        Image img = new ImageIcon(Path_Img).getImage();
        Image newImg;
        newImg = img.getScaledInstance(55, 55, java.awt.Image.SCALE_FAST);
        ImageIcon ico = new ImageIcon(newImg);
        Label_Img.setIcon(ico);
        this.contenedor = contenedor;
    }

    public String GuardarImagen(String path, String nom) {
        File destino = new File(path + nom);
        File foto = new File(Path_Img);
        try {
            FileController.copiarArchivo(foto, destino);
            return destino.getPath();
        } catch (IOException ex) {
            Logger.getLogger(ComponenteImagen.class.getName()).log(Level.SEVERE, null, ex);
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Label_Img = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setMaximumSize(new java.awt.Dimension(230, 55));
        setMinimumSize(new java.awt.Dimension(230, 55));

        Label_Img.setMaximumSize(new java.awt.Dimension(55, 55));
        Label_Img.setMinimumSize(new java.awt.Dimension(55, 55));
        Label_Img.setPreferredSize(new java.awt.Dimension(55, 55));
        Label_Img.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Label_ImgMouseClicked(evt);
            }
        });

        jButton1.setText("Borrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Label_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Label_Img, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        contenedor.borrarImagen(this.index);
        contenedor.validate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Label_ImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Label_ImgMouseClicked

        java.awt.Dimension D = new java.awt.Dimension(800, 600);
        Image img = new ImageIcon(Path_Img).getImage();
        Image newImg;
        newImg = img.getScaledInstance(D.width, D.height, java.awt.Image.SCALE_AREA_AVERAGING);
        ImageIcon ico = new ImageIcon(newImg);
        JLabel I = new JLabel();
        I.setIcon(ico);
        JDialog d = new JDialog(this.contenedor.RR.ventanaPrincipal, true);
        d.setLocationByPlatform(true);
        d.setMaximumSize(D);
        d.setMinimumSize(D);
        // d.setPreferredSize(new java.awt.Dimension(479, 306));
        d.add(I);
        d.setVisible(true);
    }//GEN-LAST:event_Label_ImgMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Img;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
