/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.DataTypes.DataPromocion;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jean
 */
public class ComponenteProductoPromocion extends javax.swing.JPanel {

    /**
     * Creates new form ComponenteProducto
     */
    private final DataPromocion P;
    private int cantidad = 1;

    private PanelProductos PP;

    public ComponenteProductoPromocion(DataPromocion Pr, PanelProductos PP) {
        this.P = Pr;
        this.PP = PP;
        initComponents();
        Nombre.setText(P.getNombre());
        if (!P.getImagen().equals("sin_imagen")) {
            Image img = new ImageIcon(P.getImagen()).getImage();
            Image newImg;
            newImg = img.getScaledInstance(78, 78, java.awt.Image.SCALE_AREA_AVERAGING);
            ImageIcon ico = new ImageIcon(newImg);
            IMG.setText("");
            IMG.setIcon(ico);
        }
    }

    public DataPromocion getProducto() {
        return P;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IMG = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(218, 82));
        setMinimumSize(new java.awt.Dimension(218, 82));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        IMG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IMG.setText("SIN IMAGEN");
        IMG.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        IMG.setMaximumSize(new java.awt.Dimension(78, 78));
        IMG.setMinimumSize(new java.awt.Dimension(78, 78));
        IMG.setPreferredSize(new java.awt.Dimension(78, 78));

        Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre.setText("Nombre");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(IMG, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(IMG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        try {
            cantidad = Integer.parseInt(JOptionPane.showInputDialog("Ingrese Cantidad"));
            this.setVisible(false);
            PP.agregarProductoaLista(this, P, cantidad);
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null, "Cantidad invalida", "ENTRADA INCORRECTA", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IMG;
    private javax.swing.JLabel Nombre;
    // End of variables declaration//GEN-END:variables
}
