/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import Logica.Categoria;
import Logica.Cliente;
import Logica.Estado;
import Logica.Individual;
import Logica.ProdPedido;
import Logica.Promocion;
import Logica.Restaurante;
import java.sql.Date;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeCellRenderer;

/**
 *
 * @author Jean
 */
public class RegistroPedido extends javax.swing.JInternalFrame {

    QuickOrder ventanaPrincipal;
    /*nodos Para el arbol*/
    DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Categorias");
    DefaultMutableTreeNode nodoCategoria;
    DefaultMutableTreeNode nodoRestaurante;
    /*categorias para el arbol*/
    HashMap Categorias;
    /*modelo para la tabla*/
    DefaultTableModel modeloTabla;

    /*Lista de los productos ProdPromo*/
    HashMap LineasPedido;
    Restaurante restaurante;

    public RegistroPedido(QuickOrder vp) throws SQLException {
        this.ventanaPrincipal = vp;
        initComponents();
        modeloTabla = new DefaultTableModel();

        this.Categorias = ventanaPrincipal.CU.getCategorias();
        ScrollProductos.setViewportView(new JPanel());
        LineasPedido = new HashMap();
        cargarArbol();
        cargarClientes();
        limpiarTabla();
        ArbolRestaurantes.setEnabled(false);
        TablaSubProductos.setModel(modeloTabla);
        this.setLocation(200, 50);
        this.show();
    }

    private void cargarArbol() {
        Iterator it = Categorias.entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry entry = (Map.Entry) it.next();
            String nombreCategoria = (String) entry.getValue();
            nodoCategoria = new DefaultMutableTreeNode(nombreCategoria);
            HashMap rest = ventanaPrincipal.CU.consultarRestaurantesPorCategoria(nombreCategoria);
            Iterator it2 = rest.entrySet().iterator();
            while (it2.hasNext()) {
                Map.Entry entry2 = (Map.Entry) it2.next();
                Restaurante R = (Restaurante) entry2.getValue();
                nodoRestaurante = new DefaultMutableTreeNode(R);
                nodoRestaurante.setAllowsChildren(false);
                nodoCategoria.add(nodoRestaurante);
            }
            raiz.add(nodoCategoria);
        }
        DefaultTreeModel modelo = new DefaultTreeModel(raiz);
        this.ArbolRestaurantes.setModel(modelo);
        TreeCellRenderer renderer = new RestaurantesCellRenderer();
        ArbolRestaurantes.setCellRenderer(renderer);
    }

    private void cargarClientes() throws SQLException {
        DefaultListModel model = new DefaultListModel();
        HashMap clientes = ventanaPrincipal.CU.retornarClientes();

        Iterator it = clientes.entrySet().iterator();
        while (it.hasNext()) {
            Map.Entry entry = (Map.Entry) it.next();
            Cliente C = ((Cliente) entry.getValue());
            model.addElement(C.getNickname());
        }
        ListaClientes.setModel(model);
    }

    public void agregarProductoIndividualTabla(Individual I, int c) {
        LineasPedido.put(I.getNombre(), new ProdPedido(c, I));
        modeloTabla.addRow(new Object[]{I.getNombre(), I.getDescripcion(), "Individual", I.getPrecio(), c, (I.getPrecio() * c)});
    }

    public void agregarProductoPromocionTabla(Promocion P, int c) {
        LineasPedido.put(P.getNombre(), new ProdPedido(c, P));
        modeloTabla.addRow(new Object[]{P.getNombre(), P.getDescripcion(), "Promocion", P.getPrecio(), c, (P.getPrecio() * c)});
    }

    private void limpiarTabla() {
        modeloTabla = (DefaultTableModel) TablaSubProductos.getModel();
        while (modeloTabla.getRowCount() > 0) {
            modeloTabla.removeRow(0);
        }
        LineasPedido.clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ScrollClientes = new javax.swing.JScrollPane();
        ListaClientes = new javax.swing.JList();
        ScrollRestaurantes = new javax.swing.JScrollPane();
        ArbolRestaurantes = new javax.swing.JTree();
        ScrollProductos = new javax.swing.JScrollPane();
        ScrollTabla = new javax.swing.JScrollPane();
        TablaSubProductos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ButtonAceptar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Registro Pedido");
        setMaximumSize(new java.awt.Dimension(860, 425));
        setMinimumSize(new java.awt.Dimension(860, 425));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(860, 425));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Seleccione Cliente");
        jLabel1.setToolTipText("");

        ScrollClientes.setMaximumSize(new java.awt.Dimension(192, 163));
        ScrollClientes.setMinimumSize(new java.awt.Dimension(192, 163));
        ScrollClientes.setPreferredSize(new java.awt.Dimension(192, 163));

        ListaClientes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        ListaClientes.setMinimumSize(new java.awt.Dimension(192, 163));
        ListaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaClientesMouseClicked(evt);
            }
        });
        ListaClientes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                ListaClientesValueChanged(evt);
            }
        });
        ScrollClientes.setViewportView(ListaClientes);

        ScrollRestaurantes.setMaximumSize(new java.awt.Dimension(151, 163));
        ScrollRestaurantes.setMinimumSize(new java.awt.Dimension(151, 163));
        ScrollRestaurantes.setPreferredSize(new java.awt.Dimension(151, 163));

        ArbolRestaurantes.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                ArbolRestaurantesValueChanged(evt);
            }
        });
        ScrollRestaurantes.setViewportView(ArbolRestaurantes);

        ScrollProductos.setMaximumSize(new java.awt.Dimension(476, 163));
        ScrollProductos.setMinimumSize(new java.awt.Dimension(476, 163));
        ScrollProductos.setPreferredSize(new java.awt.Dimension(476, 163));

        TablaSubProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Descripcion", "Tipo", "Precio", "Cantidad", "Precio Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaSubProductos.getTableHeader().setReorderingAllowed(false);
        ScrollTabla.setViewportView(TablaSubProductos);
        if (TablaSubProductos.getColumnModel().getColumnCount() > 0) {
            TablaSubProductos.getColumnModel().getColumn(0).setResizable(false);
            TablaSubProductos.getColumnModel().getColumn(0).setPreferredWidth(100);
            TablaSubProductos.getColumnModel().getColumn(1).setResizable(false);
            TablaSubProductos.getColumnModel().getColumn(1).setPreferredWidth(200);
            TablaSubProductos.getColumnModel().getColumn(2).setResizable(false);
            TablaSubProductos.getColumnModel().getColumn(2).setPreferredWidth(5);
            TablaSubProductos.getColumnModel().getColumn(3).setResizable(false);
            TablaSubProductos.getColumnModel().getColumn(3).setPreferredWidth(5);
            TablaSubProductos.getColumnModel().getColumn(4).setResizable(false);
            TablaSubProductos.getColumnModel().getColumn(4).setPreferredWidth(5);
            TablaSubProductos.getColumnModel().getColumn(5).setResizable(false);
            TablaSubProductos.getColumnModel().getColumn(5).setPreferredWidth(5);
        }

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Seleccione Restaurante");
        jLabel2.setToolTipText("");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Seleccione Productos");
        jLabel3.setToolTipText("");

        ButtonAceptar.setText("Aceptar");
        ButtonAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAceptarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollTabla)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ScrollClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ScrollRestaurantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ScrollProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonAceptar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ScrollClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ScrollRestaurantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ScrollProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonAceptar)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        ventanaPrincipal.setOperando(false);
        this.dispose();
    }//GEN-LAST:event_formInternalFrameClosing

    private void ListaClientesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_ListaClientesValueChanged
        ArbolRestaurantes.setEnabled(true);
    }//GEN-LAST:event_ListaClientesValueChanged

    private void ArbolRestaurantesValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_ArbolRestaurantesValueChanged
        if (evt.getNewLeadSelectionPath() == null) {
            return;
        }
        DefaultMutableTreeNode x = (DefaultMutableTreeNode) evt.getNewLeadSelectionPath().getLastPathComponent();
        if (x.getAllowsChildren() == false) {
            restaurante = (Restaurante) x.getUserObject();
            PanelProductos PP = new PanelProductos(this);
            PP.iniciarPanel(ventanaPrincipal.CU.getCP().buscarProductosI(restaurante), ventanaPrincipal.CU.getCP().buscarProductosP((Restaurante) x.getUserObject()));
            ScrollProductos.setViewportView(PP);
            limpiarTabla();
        }
    }//GEN-LAST:event_ArbolRestaurantesValueChanged

    private void ListaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaClientesMouseClicked

    }//GEN-LAST:event_ListaClientesMouseClicked

    private void ButtonAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAceptarActionPerformed
        try {
            ventanaPrincipal.CU.insertarPedido(0, new Date(10,10,1990), Estado.preparacion, ventanaPrincipal.CU.buscarCliente((ListaClientes.getSelectedValue().toString())),  restaurante, LineasPedido);
        } catch (Exception ex) {
             JOptionPane.showMessageDialog(null, ex.getMessage(), "!ERROR¡", JOptionPane.ERROR_MESSAGE);
           
            Logger.getLogger(RegistroPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_ButtonAceptarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree ArbolRestaurantes;
    private javax.swing.JButton ButtonAceptar;
    private javax.swing.JList ListaClientes;
    private javax.swing.JScrollPane ScrollClientes;
    private javax.swing.JScrollPane ScrollProductos;
    private javax.swing.JScrollPane ScrollRestaurantes;
    private javax.swing.JScrollPane ScrollTabla;
    private javax.swing.JTable TablaSubProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
